SEED_SUPPLIERS = [
  {
    "name": "Молочный комбинат Екатеринбургский",
    "category": "Молочная продукция",
    "city": "Екатеринбург",
    "inn": "6670123456",
    "legal_name": "ООО Молочный комбинат Екатеринбургский",
    "legal_address": "г. Екатеринбург, ул. Промышленная, д. 14",
    "director_name": "Иванов Сергей Николаевич",
    "reg_date": "2008-03-15",
    "legal_status": "Действующее",
    "is_verified": True,
    "is_risky": False,
    "phones": ["+73432510034", "+73432510035"],
    "emails": ["opt@milk-ekb.ru"],
    "website": "https://milk-ekb.ru",
    "has_certificate": True,
    "cert_types": ["ГОСТ Р 52090", "ISO 22000"],
    "is_manufacturer": True,
    "has_delivery": True,
    "has_pickup": True,
    "payment_delay_days": 14,
    "min_order_kg": 100,
    "min_order_rub": 15000,
    "score": 92,
    "description": "Собственное производство полного цикла. Молоко, кефир, сметана, творог, сыры. Поставки в сети HoReCa Уральского региона с 2008 года.",
    "source_type": "manual"
  },
  {
    "name": "АгроМясо Урал",
    "category": "Мясо и птица",
    "city": "Екатеринбург",
    "inn": "6674234567",
    "legal_name": "ООО АгроМясо Урал",
    "legal_address": "г. Екатеринбург, ул. Мясников, д. 3",
    "director_name": "Петров Андрей Викторович",
    "reg_date": "2011-07-22",
    "legal_status": "Действующее",
    "is_verified": True,
    "is_risky": False,
    "phones": ["+73432671122"],
    "emails": ["zakupki@agromyaso-ural.ru"],
    "website": "https://agromyaso-ural.ru",
    "has_certificate": True,
    "cert_types": ["Ветеринарное свидетельство", "ХАССП"],
    "is_manufacturer": True,
    "has_delivery": True,
    "has_pickup": False,
    "payment_delay_days": 7,
    "min_order_kg": 50,
    "min_order_rub": 20000,
    "score": 87,
    "description": "Поставки охлаждённой и замороженной говядины, свинины, птицы. Собственный забойный цех. Ветеринарные сопроводительные документы на каждую партию.",
    "source_type": "manual"
  },
  {
    "name": "ФрешОвощи Логистик",
    "category": "Овощи и фрукты",
    "city": "Москва",
    "inn": "7743345678",
    "legal_name": "ООО ФрешОвощи Логистик",
    "legal_address": "г. Москва, Каширское шоссе, д. 61, стр. 2",
    "director_name": "Сидоров Михаил Александрович",
    "reg_date": "2015-01-10",
    "legal_status": "Действующее",
    "is_verified": True,
    "is_risky": False,
    "phones": ["+74952341122", "+74952341133"],
    "emails": ["sales@fresh-ovoshi.ru"],
    "website": "https://fresh-ovoshi.ru",
    "has_certificate": True,
    "cert_types": ["Фитосанитарный сертификат", "Декларация ТР ТС"],
    "is_manufacturer": False,
    "has_delivery": True,
    "has_pickup": True,
    "payment_delay_days": 21,
    "min_order_kg": 200,
    "min_order_rub": 30000,
    "score": 78,
    "description": "Оптовые поставки овощей и фруктов из Краснодарского края, Узбекистана, Турции. Собственные холодильные склады 3000 кв.м. Доставка рефрижератором по всей России.",
    "source_type": "manual"
  },
  {
    "name": "РыбОпт Северный",
    "category": "Рыба и морепродукты",
    "city": "Санкт-Петербург",
    "inn": "7801456789",
    "legal_name": "ООО РыбОпт Северный",
    "legal_address": "г. Санкт-Петербург, Рыбный переулок, д. 2",
    "director_name": "Козлов Дмитрий Иванович",
    "reg_date": "2009-05-18",
    "legal_status": "Действующее",
    "is_verified": True,
    "is_risky": False,
    "phones": ["+78124561234"],
    "emails": ["opt@ryb-opt.ru"],
    "website": "https://ryb-opt.ru",
    "has_certificate": True,
    "cert_types": ["Ветеринарное свидетельство", "ХАССП", "MSC"],
    "is_manufacturer": True,
    "has_delivery": True,
    "has_pickup": True,
    "payment_delay_days": 14,
    "min_order_kg": 30,
    "min_order_rub": 25000,
    "score": 89,
    "description": "Поставки охлаждённой и замороженной рыбы: сёмга, форель, треска, минтай. Собственная переработка. Поставки в рестораны и сети HoReCa с 2009 года.",
    "source_type": "manual"
  },
  {
    "name": "УралХлеб",
    "category": "Хлеб и выпечка",
    "city": "Екатеринбург",
    "inn": "6672567890",
    "legal_name": "ООО УралХлеб",
    "legal_address": "г. Екатеринбург, ул. Хлебная, д. 7",
    "director_name": "Новикова Елена Сергеевна",
    "reg_date": "2003-11-30",
    "legal_status": "Действующее",
    "is_verified": True,
    "is_risky": False,
    "phones": ["+73432891011"],
    "emails": ["zakaz@uralhleb.ru"],
    "website": "https://uralhleb.ru",
    "has_certificate": True,
    "cert_types": ["ГОСТ 31805", "ISO 9001"],
    "is_manufacturer": True,
    "has_delivery": True,
    "has_pickup": False,
    "payment_delay_days": 0,
    "min_order_kg": 20,
    "min_order_rub": 5000,
    "score": 83,
    "description": "Хлебозавод полного цикла. Хлеб, батоны, сдоба, пряники. Ежедневная доставка свежей продукции в магазины и рестораны Екатеринбурга и области.",
    "source_type": "manual"
  },
  {
    "name": "ПакФуд Решения",
    "category": "Упаковка",
    "city": "Москва",
    "inn": "7736678901",
    "legal_name": "ООО ПакФуд Решения",
    "legal_address": "г. Москва, ул. Складочная, д. 1 стр. 9",
    "director_name": "Громов Павел Олегович",
    "reg_date": "2017-04-05",
    "legal_status": "Действующее",
    "is_verified": True,
    "is_risky": False,
    "phones": ["+74957891234"],
    "emails": ["info@pakfood.ru"],
    "website": "https://pakfood.ru",
    "has_certificate": True,
    "cert_types": ["Декларация ТР ТС 005/2011"],
    "is_manufacturer": False,
    "has_delivery": True,
    "has_pickup": True,
    "payment_delay_days": 30,
    "min_order_kg": None,
    "min_order_rub": 10000,
    "score": 71,
    "description": "Пищевая упаковка оптом: контейнеры ПЭТ, стаканы, крышки, ламинированный картон. Работаем с HoReCa и ритейлом. Отсрочка 30 дней для постоянных клиентов.",
    "source_type": "manual"
  }
]
